const trip = [
 {date:'Sun, Aug 30',title:'Arrive in Ireland & Galway Evening',summary:'Dublin Airport to Galway, check in, then an easy first evening in the Latin Quarter.',overnight:'Galway City Centre',stops:[
  {time:'11:55 AM',name:'Dublin Airport',lat:53.4264,lng:-6.2499,desc:'Land, clear immigration, collect luggage and rental car.',guide:'Take a few minutes before leaving the rental lot to set mirrors, learn the roundabouts, and remember that the driver sits nearest the center line.',tips:['Allow 90 minutes','Drive on the left','Download offline maps']},
  {time:'1:30 PM',name:'Drive to Galway',lat:53.2707,lng:-9.0568,desc:'Use the M50/M4/M6 motorway corridor west.',guide:'The motorway portion is the easiest driving of the trip. Service areas are available en route; avoid pushing through fatigue after the overnight flight.',tips:['Approx. 2 hr 30 min','Motorway tolls']},
  {time:'4:30 PM',name:'Galway City Centre',lat:53.2727,lng:-9.0538,desc:'Check in and walk the Latin Quarter, Quay Street and Spanish Arch.',guide:'Galway grew around the River Corrib and its medieval merchant families. Look for the colorful shopfronts, buskers and remnants of the old city walls.',tips:['Walkable evening','Early dinner','Overnight: Galway']}
 ]},
 {date:'Mon, Aug 31',title:'Medieval Ruins, Cong & Mayo',summary:'Leave Galway for one of Ireland’s finest friary ruins, then settle into Cong.',overnight:'Ryan’s Riverlodge B&B, Cong',stops:[
  {time:'9:00 AM',name:'Depart Galway',lat:53.2707,lng:-9.0568,desc:'Check out and head north toward Headford.',guide:'Today shifts from city Ireland into the limestone, lake and farmland landscape around Lough Corrib.',tips:['Fuel before departure']},
  {time:'10:00 AM',name:'Ross Errilly Friary',lat:53.4699,lng:-9.1191,desc:'Explore the remarkably complete Franciscan friary near Headford.',guide:'Founded in the medieval period, the complex preserves two cloisters, church, tower and domestic rooms. Imagine the site functioning as a self-contained religious community rather than merely a ruined church.',tips:['Uneven ground','Allow 60–75 min','Free/open ruin']},
  {time:'12:00 PM',name:'Cong Village',lat:53.5413,lng:-9.2861,desc:'Lunch and village walk near the River Cong.',guide:'Cong sits between Lough Corrib and Lough Mask. Visit the abbey ruins and the riverside paths; film fans will recognize the village from The Quiet Man.',tips:['Lunch stop','Easy walking']},
  {time:'3:00 PM',name:'Ryan’s Riverlodge B&B',lat:53.5416,lng:-9.2854,desc:'Check in and enjoy an unhurried evening in Cong.',guide:'Use the evening to confirm the next day’s sheepdog demonstration and organize rain gear, camera and genealogy notes.',tips:['Overnight: Cong','Confirm check-in time']}
 ]},
 {date:'Tue, Sep 1',title:'Joyce Country Sheepdogs & Connemara',summary:'A signature day through Joyce Country, with the working sheep farm and Dogs Bay.',overnight:'Ryan’s Riverlodge B&B, Cong',stops:[
  {time:'9:00 AM',name:'Depart Cong',lat:53.5413,lng:-9.2861,desc:'Scenic drive west through Joyce Country.',guide:'The landscape between Cong, Maam and Leenane is closely associated with the Joyce surname and the historic territory called Joyce Country.',tips:['Narrow roads','Photo pull-offs']},
  {time:'10:40 AM',name:'Joyce Country Sheepdogs',lat:53.5268,lng:-9.7356,desc:'Arrive before the 11:00 AM working sheepdog demonstration.',guide:'Watch how voice and whistle commands direct Border Collies across open ground. The farm demonstrates living agricultural traditions rather than a staged animal show.',tips:['11:00 AM demo','Arrive early','Outdoor clothing']},
  {time:'12:30 PM',name:'Leenane',lat:53.5952,lng:-9.6940,desc:'Lunch beside Killary Harbour.',guide:'Killary is commonly described as Ireland’s only true fjord. The steep valley reflects ancient glacial action and forms one of the West’s most dramatic road corridors.',tips:['Lunch','Harbour views']},
  {time:'3:00 PM',name:'Dogs Bay Beach',lat:53.3985,lng:-9.9564,desc:'Walk the pale shell-sand crescent near Roundstone.',guide:'The sand is formed largely from tiny shell fragments rather than ordinary rock grains. Gurteen Bay lies back-to-back across the narrow tombolo.',tips:['Windy','No swimming required','Allow 45–60 min']},
  {time:'6:15 PM',name:'Return to Cong',lat:53.5413,lng:-9.2861,desc:'Scenic return to your B&B.',guide:'Keep the evening flexible; western Irish roads often take longer than mileage suggests.',tips:['Overnight: Cong']}
 ]},
 {date:'Wed, Sep 2',title:'Castlebar, Mayo Heritage & Ancient Sites',summary:'A County Mayo day combining family-history research, Castlebar and older monuments.',overnight:'Ryan’s Riverlodge B&B, Cong',stops:[
  {time:'9:00 AM',name:'Castlebar',lat:53.8550,lng:-9.2879,desc:'Explore the county town and pursue Joyce family-history leads.',guide:'Castlebar is an ideal base for consulting County Mayo repositories and orienting yourself to parishes, civil registration districts and historic land records.',tips:['Bring family names','Photograph records','Allow 2 hours']},
  {time:'11:00 AM',name:'Mayo County Library',lat:53.8566,lng:-9.2962,desc:'Local studies and genealogy research stop.',guide:'Ask specifically about Griffith’s Valuation, revision books, parish histories, estate papers, graveyard surveys and Joyce households around Castlebar and Joyce Country.',tips:['Verify hours','Bring ID','Take citations']},
  {time:'1:30 PM',name:'National Museum of Ireland – Country Life',lat:53.8838,lng:-9.2197,desc:'Learn how rural Irish families lived and worked.',guide:'The museum’s collections help translate census occupations and land records into daily life—housing, farming, trades, clothing and seasonal customs.',tips:['Indoor stop','Lunch nearby']},
  {time:'4:00 PM',name:'Ballymagibbon Cairn',lat:53.5103,lng:-9.3368,desc:'Optional ancient monument near Cong.',guide:'This prehistoric cairn adds a quiet archaeological stop close to your base. Treat the landscape respectfully and avoid climbing unstable stonework.',tips:['Optional','Brief stop','Uneven ground']},
  {time:'5:00 PM',name:'Cong Abbey',lat:53.5405,lng:-9.2860,desc:'Finish among the abbey ruins and riverside paths.',guide:'The surviving remains are largely medieval, though the religious history of Cong is older. Notice the carved stonework and the abbey’s relationship to the water.',tips:['Golden-hour photos','Overnight: Cong']}
 ]},
 {date:'Thu, Sep 3',title:'Newgrange, Hill of Tara & Howth',summary:'Cross Ireland for the great Neolithic landscape of the Boyne Valley, then continue to Howth.',overnight:'Howth',stops:[
  {time:'7:15 AM',name:'Depart Cong',lat:53.5413,lng:-9.2861,desc:'Early departure east toward County Meath.',guide:'This is the longest transfer day. Your Newgrange ticket time should control the schedule.',tips:['Early breakfast','Pre-book Newgrange']},
  {time:'11:00 AM',name:'Brú na Bóinne Visitor Centre',lat:53.6947,lng:-6.4463,desc:'Required starting point for Newgrange and Knowth guided visits.',guide:'Newgrange was built around 3200 BC. Its passage and chamber are aligned so winter-solstice sunrise enters through the roof-box. The entrance stone’s spirals remain undeciphered; interpretations include cosmology, ritual, cycles and territorial identity.',tips:['Advance ticket essential','Arrive 30 min early','Tour by shuttle']},
  {time:'2:45 PM',name:'Hill of Tara',lat:53.5789,lng:-6.6111,desc:'Walk the ceremonial landscape of Ireland’s High Kings.',guide:'Tara is not a single monument but a layered ritual landscape. Seek out the Mound of the Hostages, the earthworks and the Lia Fáil, or Stone of Destiny.',tips:['Visitor centre 10–5','Open landscape','Waterproof shoes']},
  {time:'5:15 PM',name:'Howth',lat:53.3858,lng:-6.0647,desc:'Check in and enjoy the harbour for dinner.',guide:'Howth’s harbour, fishing village and cliff peninsula make a relaxing final base near Dublin Airport.',tips:['Seafood dinner','Overnight: Howth']}
 ]},
 {date:'Fri, Sep 4',title:'Howth Morning & Departure',summary:'A flexible final morning near Dublin Airport.',overnight:'Departure day',stops:[
  {time:'8:00 AM',name:'Howth Harbour',lat:53.3892,lng:-6.0668,desc:'Breakfast and a short harbour walk.',guide:'Look for fishing boats, Ireland’s Eye offshore and the lighthouse at the harbour mouth. Keep the walk short enough to protect your airport buffer.',tips:['Check flight time','Pack before walking']},
  {time:'9:00 AM',name:'Howth Cliff Walk Viewpoint',lat:53.3778,lng:-6.0533,desc:'Optional brief coastal viewpoint rather than the full loop.',guide:'The peninsula’s cliffs reveal the geology and maritime character of Dublin Bay. Use a nearby viewpoint if weather or time makes the full trail impractical.',tips:['Optional','Slippery when wet']},
  {time:'TBD',name:'Dublin Airport',lat:53.4264,lng:-6.2499,desc:'Return rental car and check in for your flight.',guide:'For a transatlantic departure, allow additional time for rental-car return, security and U.S. preclearance.',tips:['Confirm flight','Allow generous buffer']}
 ]}
];

let currentDay=0, map, markers=[], routeLine, deferredPrompt;
const $=s=>document.querySelector(s);
const dayTabs=$('#dayTabs'), stopList=$('#stopList'), modal=$('#modal');
function appleLink(s){return `https://maps.apple.com/?daddr=${s.lat},${s.lng}&dirflg=d`}
function googleLink(s){return `https://www.google.com/maps/dir/?api=1&destination=${s.lat},${s.lng}`}
function routeLink(day){return `https://www.google.com/maps/dir/?api=1&destination=${day.stops.at(-1).lat},${day.stops.at(-1).lng}&waypoints=${day.stops.slice(0,-1).map(s=>`${s.lat},${s.lng}`).join('|')}`}
function init(){
 dayTabs.innerHTML='';trip.forEach((d,i)=>{let b=document.createElement('button');b.textContent=`Day ${i+1} · ${d.date.split(',')[0]}`;b.onclick=()=>renderDay(i);dayTabs.appendChild(b)});
 map=L.map('map',{zoomControl:true}).setView([53.6,-8.2],7);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);
 renderDay(0); setupTools();
 if('serviceWorker' in navigator) navigator.serviceWorker.register('sw.js');
}
function renderDay(i){currentDay=i;const d=trip[i];[...dayTabs.children].forEach((b,j)=>b.classList.toggle('active',i===j));
 $('#dayLabel').textContent=`DAY ${i+1} · ${d.date.toUpperCase()}`;$('#dayTitle').textContent=d.title;$('#daySummary').textContent=d.summary;$('#routeBtn').href=routeLink(d);
 markers.forEach(m=>map.removeLayer(m));markers=[];if(routeLine)map.removeLayer(routeLine);stopList.innerHTML='';let coords=[];
 d.stops.forEach((s,n)=>{coords.push([s.lat,s.lng]);let m=L.marker([s.lat,s.lng]).addTo(map).bindPopup(`<b>${n+1}. ${s.name}</b><br>${s.time}`);markers.push(m);
  const node=$('#stopTemplate').content.cloneNode(true),card=node.querySelector('.stop-card'),box=node.querySelector('.done-box');
  node.querySelector('.stop-number').textContent=n+1;node.querySelector('.stop-time').textContent=s.time;node.querySelector('.stop-name').textContent=s.name;node.querySelector('.stop-description').textContent=s.desc;node.querySelector('.guide-notes').textContent=s.guide;
  node.querySelector('.tips').innerHTML=s.tips.map(t=>`<span class="tip">${t}</span>`).join('');node.querySelector('.apple').href=appleLink(s);node.querySelector('.google').href=googleLink(s);
  const key=`done-${i}-${n}`;box.checked=localStorage.getItem(key)==='1';card.classList.toggle('completed',box.checked);box.onchange=()=>{localStorage.setItem(key,box.checked?'1':'0');card.classList.toggle('completed',box.checked);updateProgress()};
  node.querySelector('.more').onclick=()=>showStop(s);stopList.appendChild(node);
 });routeLine=L.polyline(coords,{weight:4,opacity:.7}).addTo(map);map.fitBounds(coords,{padding:[30,30]});updateProgress();
}
function updateProgress(){const boxes=[...document.querySelectorAll('.done-box')],done=boxes.filter(b=>b.checked).length;$('#progressText').textContent=`${done} of ${boxes.length} completed`}
function showStop(s){showModal(`<p class="eyebrow">DESTINATION GUIDE</p><h2>${s.name}</h2><p><b>Planned time:</b> ${s.time}</p><p>${s.desc}</p><h3>What to notice</h3><p>${s.guide}</p><div class="tips">${s.tips.map(t=>`<span class="tip">${t}</span>`).join('')}</div><p><a class="primary" href="${appleLink(s)}" target="_blank">Navigate with Apple Maps</a></p>`) }
function showModal(html){$('#modalContent').innerHTML=html;modal.showModal()}
function setupTools(){document.querySelector('.close').onclick=()=>modal.close();modal.addEventListener('click',e=>{if(e.target===modal)modal.close()});
 $('#resetBtn').onclick=()=>{trip[currentDay].stops.forEach((_,n)=>localStorage.removeItem(`done-${currentDay}-${n}`));renderDay(currentDay)};
 $('#showAllBtn').onclick=()=>showModal(`<p class="eyebrow">FULL ITINERARY</p><h2>Six-Day Overview</h2>${trip.map((d,i)=>`<h3>Day ${i+1}: ${d.date} — ${d.title}</h3><p>${d.stops.map(s=>`${s.time} ${s.name}`).join(' · ')}</p><p><b>Overnight:</b> ${d.overnight}</p>`).join('')}`);
 $('#genealogyBtn').onclick=()=>showModal(`<p class="eyebrow">JOYCE FAMILY RESEARCH</p><h2>Castlebar Research Checklist</h2><div class="modal-grid"><p><b>Known ancestor:</b> John M. Joyce, born about 1860 in Ireland; later lived in Chicago and worked for the city water department.</p><p>Ask repositories for civil registration, parish registers, Griffith’s Valuation, valuation revision books, estate records, workhouse records, graveyard transcripts and local newspaper notices.</p><p>Search surname variants: Joyce, Joice and Joyes. Record the exact parish, townland, witnesses and sponsors from every document.</p><p>Useful trip stops: Mayo County Library Local Studies, Castlebar; churches and graveyards tied to any discovered parish; National Museum of Ireland – Country Life for historical context.</p></div>`);
 $('#emergencyBtn').onclick=()=>showModal(`<p class="eyebrow">IRELAND ESSENTIALS</p><h2>Travel Quick Reference</h2><p><b>Emergency services:</b> 112 or 999</p><p><b>Driving:</b> Keep left. At roundabouts, yield to traffic from the right. Distances and speed limits are in kilometres.</p><p><b>Weather:</b> Carry a waterproof layer even on clear mornings.</p><p><b>Newgrange:</b> Entry begins at Brú na Bóinne Visitor Centre; monument access is guided and advance booking is essential.</p><p><b>Offline:</b> Save offline areas in Apple or Google Maps before departure.</p>`);
 $('#notesBtn').onclick=()=>{showModal(`<p class="eyebrow">PRIVATE NOTES</p><h2>My Trip Notes</h2><textarea id="noteArea" class="note-area" placeholder="Confirmation numbers, family discoveries, restaurants, memories…">${localStorage.getItem('tripNotes')||''}</textarea><p><button id="saveNotes" class="primary">Save Notes</button></p>`);$('#saveNotes').onclick=()=>{localStorage.setItem('tripNotes',$('#noteArea').value);modal.close()}};
 window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').hidden=true}};
}
init();
